Integrate BDP UI Library Footer into BDP Website
bitcoin-dev-project/bitcoin-dev-project pull request #127
Opened 2024-11-14 11:32 UTC by jrakibi

This PR adds the footer component from the BDP UI library to the BDP website

https://www.npmjs.com/package/@bitcoin-dev-project/bdp-ui

2024-11-14 13:41 UTC, Emmanuel-Develops commented on components/footer-component.tsx
> +function Wrapper({
Curious did you use `max-md` due to conflicting styles?

2024-11-14 15:36 UTC, aassoiants commented
Also to include: https://www.linkedin.com/company/bitcoin-dev-project/

2024-11-15 09:52 UTC, jrakibi commented on components/footer-component.tsx
> +function Wrapper({
- 'Good First Issue' and 'Decoding Bitcoin' use full-width layouts, which is why I've used the `Wrapper` component, similar to what we have for the transcript registry. I think using a full-width footer on the homepage looks fine, unless we decide to make it dynamic (using max-w-7xl on the homepage and full width for Decoding and Good First Issue
- I've  removed `max-md`

2024-11-15 09:54 UTC, jrakibi commented
> Also to include: https://www.linkedin.com/company/bitcoin-dev-project/

@Emmanuel-Develops I think this should be added on the library level, right ? 
we don't have linkedin on the list

2024-11-15 10:50 UTC, Emmanuel-Develops commented
> > Also to include: https://www.linkedin.com/company/bitcoin-dev-project/
> 
> @Emmanuel-Develops I think this should be added on the library level, right ? we don't have linkedin on the list

not necessarily, I made it very customizable so you can extend with custom SM e.g linkedIn doing something like this:
```
{
              entity: "linkedIn",
              entityLink: "https://www.linkedin.com/company/bitcoin-devs/",
              iconProps: {
                className: "hover:text-orange-400",
              },
              icon: <LinkedInIcon className="w-full h-full" />,
}
```
tldr: if you provide your own icon you can support any arbitrary SM entity.

I need to invest in documentation 😅

2024-11-15 11:33 UTC, jrakibi commented
> > > Also to include: https://www.linkedin.com/company/bitcoin-dev-project/
> > 
> > 
> > @Emmanuel-Develops I think this should be added on the library level, right ? we don't have linkedin on the list
> 
> not necessarily, I made it very customizable so you can extend with custom SM e.g linkedIn doing something like this:
> 
> ```
> {
>               entity: "linkedIn",
>               entityLink: "https://www.linkedin.com/company/bitcoin-devs/",
>               iconProps: {
>                 className: "hover:text-orange-400",
>               },
>               icon: <LinkedInIcon className="w-full h-full" />,
> }
> ```
> 
> tldr: if you provide your own icon you can support any arbitrary SM entity.
> 
> I need to invest in documentation 😅

Thanks you, done

2024-11-15 15:03 UTC, Emmanuel-Develops requested changes
The icon doesn't take the full width of the container
<img width="335" alt="Screenshot 2024-11-15 at 4 03 17 PM" src="https://github.com/user-attachments/assets/f0ba2cf4-9306-4356-a011-ec8b886010c0">

2024-11-15 15:03 UTC, Emmanuel-Develops commented on components/footer-component.tsx
> +                                icon: <LinkedinIcon className="w-full h-full" />
```suggestion
                                icon: <LinkedinIcon className="w-full h-full" />
                                icon: <LinkedinIcon width="100%" height="100%" />
```

2024-11-15 16:52 UTC, Emmanuel-Develops commented
also ideally you'd want to import the library CSS globally, so that custom classes and colors apply
```tsx
// app/layout.tsx
import { Barlow } from "next/font/google"
import type { Metadata } from "next"
import "@bitcoin-dev-project/bdp-ui/styles.css" // add the library styles here before global css
import "./globals.css"
...
```

2025-01-15 12:48 UTC, Emmanuel-Develops approved these changes

2025-01-15 13:14 UTC, merged