feat: Add Community Cohort Dashboard and Navigation
bitcoin-dev-project/bitcoin-dev-project pull request #129
Opened 2024-11-24 12:08 UTC by jrakibi

Implements community cohort functionality including dashboard views, navigation, and progress tracking

Tasks completed:
- [x] Create community data structure with cohort tracking
- [x] Create cohort component with:
  - Weekly progress tracking
  - Implemented weekly call scheduling and calendar integration

<img width="2038" alt="image" src="https://github.com/user-attachments/assets/ed1d931c-8417-49d7-85a9-b759d1dbb8a7">

2024-12-11 18:30 UTC, Emmanuel-Develops commented
There is a build issue

<img width="1235" alt="Screenshot 2024-12-11 at 9 22 35 PM" src="https://github.com/user-attachments/assets/44e84c6c-a4a5-4a02-ac38-647685ff0953" />

2024-12-23 13:42 UTC, Emmanuel-Develops requested changes
Looks awesome!

A couple of nits.

Also structure wise, it will be easier if the community page (i.e `/decoding/communities/bitcoin-indonesia`) is server rendered and then each component defined in that page is abstracted into their own components.
Makes it easy to jump across references and isolated components

2024-12-23 13:42 UTC, Emmanuel-Develops commented on app/decoding/communities/[communityId]/page.tsx
> +                                                getCurrentWeek(communityData)
`getCurrentWeek` is called multiple times
we can initialise it higher up and use that data when we need it

2024-12-23 13:42 UTC, Emmanuel-Develops commented on app/decoding/communities/[communityId]/page.tsx
> +    if (!communityData || !currentWeekData) {
This page would be better suited as a server component.
So we generate all possible community pages on build and then it is easy to throw not found for community routes that do not exist.
the current approach returns "Loading"

also with the page rendered as a server component we get the data on the server and then pass them to client/server components.
Removes the need for useState and useEffect to store communityData and currentWeekData

2024-12-24 14:46 UTC, jrakibi commented
Thanks @Emmanuel-Develops for reviewing

I believe all the feedback has been addressed
I’ve also separated each component into its own file for easier reference

2025-01-15 01:28 UTC, Emmanuel-Develops approved these changes

2025-01-15 01:28 UTC, merged