add umami analytics to app
bitcoin-dev-project/bitcoin-dev-project pull request #64
Opened 2024-06-11 10:54 UTC by IgboPharaoh

Adds umami analytics to app

2024-06-11 12:20 UTC, Extheoisah requested changes
Looks good. Just a few nits.
We should also disable tracking when not in prod so that we don't have skewed data that is mixed. Here's a template you can modify for this
```js
export const disableUmamiTrack = () => {
    if (typeof window !== "undefined") {
        const disabled = localStorage.getItem("umami.disabled")
        if (process.env.VERCEL_ENV !== "production") {
            if (!disabled) {
                localStorage.setItem("umami.disabled", "1")
            }
        } else if (disabled) {
            localStorage.removeItem("umami.disabled")
        }
    }
}
```
See the bottom of the docs here https://umami.is/docs/track-events

2024-06-11 12:20 UTC, Extheoisah commented on components/drawer.tsx
> +                            data-umami-event={`navigation-item-clicked`}
Let's add the link text so its recognizable at a glance on umami
```suggestion
                            data-umami-event={`nav-${link.text}-clicked`}
```

2024-06-11 12:20 UTC, Extheoisah commented on components/nav-bar.tsx
> +                                data-umami-event={`navigation-item-clicked`}
```suggestion
                                data-umami-event={`nav-${link.text}-clicked`}
```

2024-06-11 12:20 UTC, Extheoisah commented on app/career/page.tsx
> +                                            data-umami-event={`funding-org-clicked`}
I don't see the event text specific to each link in the Umami dashboard. So I suggest we add the funding source's name to the event itself. The same applies to other funding sources
```suggestion
                                            data-umami-event={`funding-org-spiral-clicked`}
```

2024-06-11 12:20 UTC, Extheoisah commented on components/pointer.tsx
> +                data-umami-event={`hero-section-cta`}
```suggestion
                data-umami-event={`hero-section-cta-${btnText}`}
```

2024-06-11 13:09 UTC, IgboPharaoh commented on app/layout.tsx
@Extheoisah For disabling tracking in other environments, I already used tracker configuration to set the data domains, I want it to get data from: https://umami.is/docs/tracker-configuration.

2024-06-12 05:33 UTC, Extheoisah approved these changes

2024-06-12 05:34 UTC, merged

2024-06-12 08:29 UTC, kouloumos commented
> We should also disable tracking when not in prod so that we don't have skewed data that is mixed

I can't see this as part of this PR

2024-06-12 08:49 UTC, Extheoisah commented
@kouloumos 

Here -> https://github.com/bitcoin-dev-project/bitcoin-dev-project/pull/64/files#diff-eca96d2c09f31517696a26e1d0be4070e1fbab02831481bed006e275741d030bR35

Used the domain to disable the tracking on any site other than bitcoindevs.xyz

2024-06-12 08:51 UTC, Extheoisah commented
> Also, umami allows you to clear analytics data. i think we should do it before getting this to production in order for the analytics during testing to be removed.

Yeah. already prompted @adamjonas for this. Pls check [discord](https://discord.com/channels/1189471179967315968/1236986988750704651/1250323839271833652)