Feat (v0-glossary): Glossary template
bitcoin-dev-project/bitcoin-dev-project pull request #79
Opened 2024-06-26 13:24 UTC by jrakibi

Integrate Tailwind/Next.js Starter Template into BDP Website

Task in this draft PR includes:
- [x]  Integrate Contentlayer for managing content logic
- [x]  Use MDX and display embedded React components within the content
- [x]  Add tags for topics
- [x]  Add SEO metadata, sitemaps, ..
- [x] Display the content of the markdown
- [x] List all topics + Pagination
- [x]  Sync the glossary files from the remote [repo](https://github.com/bitcoin-dev-project/glossary/) source to our local BDP website

2024-07-04 11:57 UTC, jrakibi commented on tsconfig.json
> -    "compilerOptions": {
done, it's formatted now

2024-07-05 06:27 UTC, Extheoisah commented on tsconfig.json
> -    "compilerOptions": {
Good point @kouloumos We should actually follow this config as opposed to the one in the transcription frontend. I'll create an issue in that repo and synchronize the prettier and ts configs across all projects.

2024-07-05 06:28 UTC, Extheoisah commented on tsconfig.json
> -    "compilerOptions": {
Even there might be differences due to the individual repo/project requirements, it should be minimal

2024-07-07 19:41 UTC, Extheoisah commented
I changed the base branch to staging instead of master branch

2024-07-17 09:50 UTC, Extheoisah commented
Is this PR ready for review? FYI, This needs rebase.

2024-07-17 09:58 UTC, jrakibi commented
> Is this PR ready for review? FYI, This needs rebase.

I will make some updates and open it for review today

2024-07-24 16:07 UTC, IgboPharaoh reviewed
Good job working on this. As this is a large pull request, I have only been able to review the code changes.
 Also across different pages, there are some comments I added relating to:
- Corrections
- Requested changes
- Questions to better understand your line of thought before further comment.

Please do well to attend to them as I test the latest deployment for this pr.

2024-07-26 10:34 UTC, jrakibi reviewed
Thanks @IgboPharaoh  for the mega-review. 
I've addressed these feedbacks in my last commits and added a few responses inline where clarification was needed.

2024-07-26 10:36 UTC, jrakibi commented on app/topics/[...slug]/page.tsx
> +    const Layout = PostBDP
Renamed to 'Topic Layout'. The idea of layouts is that we can have several ways to represent the UI for the Topic page. Currently, we have only one layout, but we can add more later. So, to make it easy for now I removed the related code and will reintroduce it once we have another layout

2024-07-26 10:36 UTC, jrakibi commented on components/bitcoin-topics/markdown-ui/script-visualizer/scriptVisualizer.tsx
> +                    {/* <div>
Removed the whole CodeWindow component, we don’t need it anymore

2024-07-26 10:38 UTC, jrakibi commented on components/bitcoin-topics/topic/PrevNextLinks.tsx
> +    dir?: "previous" | "next"
Are you referring to the `dir` variable?
If so, I've renamed it to `direction`

2024-07-29 10:49 UTC, Extheoisah commented
@jrakibi Please can you rebase this PR?

2024-07-29 12:15 UTC, IgboPharaoh commented on app/topics/[...slug]/page.tsx
> +            "@type": "Person",
Great

2024-07-29 12:16 UTC, IgboPharaoh commented on components/bitcoin-topics/topic/PrevNextLinks.tsx
> +    dir?: "previous" | "next"
Yes that was what I was referring to

2024-07-29 14:11 UTC, jrakibi commented
> @jrakibi Please can you rebase this PR?

Done

2024-08-05 21:20 UTC, IgboPharaoh commented
> @Extheoisah @IgboPharaoh
> 
> Rebased the PR

Nice, will review

2024-08-07 13:01 UTC, Extheoisah requested changes
Quite a big PR. Great work overall.
I left some comments and nits.

2024-08-08 11:17 UTC, jrakibi reviewed
Thanks for the review, @Extheoisah 

To simplify the process, I addressed each major feedback in its own commit. I hope this makes reviewing easier

I also addressed all the nits and minor updates in [commit #3413095](https://github.com/bitcoin-dev-project/bitcoin-dev-project/pull/79/commits/341309548fe02ddfd8ee0bf8f017d09022b80839) , so I haven't left individual comment replies on them

2024-08-08 11:17 UTC, jrakibi commented on tailwind.config.ts
> +        "./public/bitcoin-topics/**/*.mdx"
Yes, we will sometimes apply Tailwind styles directly within the markdown

2024-08-08 11:17 UTC, jrakibi commented on components.json
> +    "$schema": "https://ui.shadcn.com/schema.json",
I was using some components from Shadcn library, but eneded up removing them. This file is not needed anymore, deleted in [cdd7bb2](https://github.com/bitcoin-dev-project/bitcoin-dev-project/pull/79/commits/cdd7bb235e2ff7bd0b61ec02abc5089d31a9eef1)

2024-08-08 11:17 UTC, jrakibi commented on bun.lockb
It's similar to package-lock.json but faster to read and write, and more compact due to its binary format. It was accidentally pushed, so we removed it as well in  [#cdd7bb2](https://github.com/bitcoin-dev-project/bitcoin-dev-project/pull/79/commits/cdd7bb235e2ff7bd0b61ec02abc5089d31a9eef1)

2024-08-08 11:17 UTC, jrakibi commented on app/topics/page.tsx
> +    // Filter out drafts in production
Extracted this into the getTopicData() function in [commit #b92da70](https://github.com/bitcoin-dev-project/bitcoin-dev-project/pull/79/commits/b92da70fbc6bf4c9bc860d3913d2b3d5b2e1f2c7)

2024-08-09 07:55 UTC, Extheoisah commented
On mobile this long script causes an overflow
![Screenshot_20240809_085243_Samsung Internet](https://github.com/user-attachments/assets/1a001b19-5ddd-4134-88b2-75554c47b0b4)


And the script stack visualizer looks off on mobile. Although not sure what we could do about that.
![Screenshot_20240809_085324_Samsung Internet](https://github.com/user-attachments/assets/4a503fb8-2301-4fe2-9705-475612c71810)

2024-08-11 05:26 UTC, jrakibi commented
@Extheoisah This [commit](https://github.com/bitcoin-dev-project/bitcoin-dev-project/pull/79/commits/453276123e8c10f31414b39c387cbd46bacf6bc9) fixes the responsiveness issue for the script visualizer on mobile

2024-08-11 18:10 UTC, Extheoisah commented
@jrakibi In dark mode, some text are not legible
![image](https://github.com/user-attachments/assets/70a5aed0-3983-4947-b232-d8371257c8bf)

![image](https://github.com/user-attachments/assets/ed2508f4-7680-4ea0-bf00-ffe141da3c20)

2024-08-12 13:44 UTC, Extheoisah approved these changes

2024-08-12 13:44 UTC, merged